# Generated by Django 5.0.1 on 2024-01-22 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.artist')),
            ],
        ),
        migrations.CreateModel(
            name='GenreSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.genre')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.song')),
            ],
        ),
    ]
