# Generated by Django 5.0.1 on 2024-01-31 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
